RAW = 0
RM_STOP_WORDS = 1
LEMMATIZATION = 2
LEMM_WITH_RM_STOPW = 3
docs_test_dir = 'Test Set/News Articles/'
summaries_test_dir = 'Test Set/Summaries/'
docs_training_dir = 'Training Set/News Articles/'
summaries_training_dir = 'Training Set/Summaries/'
UNIGRAMS = 1
BIGRAMS = 2
